### ISSUE TITLE
Couple enhancements: folder org, input() over CLI for key

### ISSUE THREAD

**Issue by kfiresmith** [xaviablaza/stellar-paper-wallet#1]
Hi @xaviablaza,
Thanks so much for whipping this up.  Would you mind if I submitted a PR to clean up the folder organization (eg: PNGs move into an ./img/ folder), and prompt the user for the secret key via input() instead of allowing it to be a command arg which would leak the secret key into shell history?

**Comment by xaviablaza** [comment]
Sure, will merge the PR. Thank you for your additions!
