### ISSUE TITLE
error if ./output/ directory doesn't exist (with solution

### ISSUE THREAD

**Issue by beleriandcrises** [xaviablaza/stellar-paper-wallet#3]
Hello, thanks for the script!

When I start it I have as an output

```
Traceback (most recent call last):
  File "spw.py", line 66, in <module>
    design.save("./output/"+pub+".png")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1725, in save
    fp = builtins.open(filename, "w+b")
IOError: [Errno 2] No such file or directory: u'./output/GBLWV2AZM2DFUJIDYOKTLY3QJYZHPGROVVOOJTPLMAVOLFKPDDDZX2EB.png'
```

As /output/ doesn't exist.
This is how I solved it in my script. It is a small thing so I'm not sure is worth a pull request.

```
import os
try:
    os.makedirs('./output/')
except OSError:
    pass 

```

**Comment by kfiresmith** [comment]
Thanks @beleriandcrises!  I'm sure if you were willing to submit a PR that @xaviablaza would merge it.

Thanks a bunch for taking the time to bring this issue up.

**Comment by xaviablaza** [comment]
Hi @beleriandcrises! Please submit a PR for review and I'll merge your fix into the repo.

**Comment by xaviablaza** [comment]
Implemented your solution in [this commit](https://github.com/xaviablaza/stellar-paper-wallet/commit/0a3043c8bb00907c03b76375c45d266b0b0ae570).
